language: python
python:
- '2.7'
before_install:
- openssl aes-256-cbc -K $encrypted_ad2e6771f07e_key -iv $encrypted_ad2e6771f07e_iv
  -in client-secret.json.enc -out client-secret.json -d
- pip install -t lib -r requirements.txt
script:
- echo "No Script to run"
deploy:
  provider: gae
  keyfile: client-secret.json
  project: out-of-office-manager
  version: ooo-manager-1-0
  no_promote: true
